services:

  db:
    image: postgres:16
    container_name: gotcha-postgres-db
    restart: always
    environment:
      - POSTGRES_DB=gotcha-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gotcha-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: gotcha-api/gotcha-api:v1
    container_name: spring-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Database
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gotcha-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin

      # Flyway
      - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/gotcha-db
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=admin

      # AWS S3
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION:-eu-north-1}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}

      # Stripe
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID}

      # Gmail OAuth
      - GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
      - GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
      - GMAIL_REFRESH_TOKEN=${GMAIL_REFRESH_TOKEN}
      - GMAIL_SENDER_ADDRESS=${GMAIL_SENDER_ADDRESS}
      - MAIL_FROM=${GMAIL_SENDER_ADDRESS}

      # App
      - APP_FRONTEND_URL=${APP_FRONTEND_URL}
    depends_on:
      - db
    networks:
      - gotcha-network

volumes:
  postgres_data:

networks:
  gotcha-network:
    driver: bridge
