version: "3.8"


services:

  db:
    image: postgres:16
    container_name: gotcha-postgres-db
    restart: always
    environment:
      - POSTGRES_DB=gotcha-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gotcha-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: gotcha-api/gotcha-api:v1
    container_name: spring-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gotcha-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin

      - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/gotcha-db
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=admin
    depends_on:
      - db
    networks:
      - gotcha-network

volumes:
  postgres_data:

networks:
  gotcha-network:
    driver: bridge