# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.url=${SPRING_FLYWAY_URL:}
spring.flyway.user=${SPRING_FLYWAY_USER:}
spring.flyway.password=${SPRING_FLYWAY_PASSWORD:}
spring.flyway.enabled=true

# AWS S3
aws.accessKey=${AWS_ACCESS_KEY:}
aws.secretKey=${AWS_SECRET_KEY:}
aws.region=${AWS_REGION:eu-north-1}
aws.bucket.name=${AWS_BUCKET_NAME:}

# Stripe
stripe.secret.key=${STRIPE_SECRET_KEY:}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:}
stripe.price.id=${STRIPE_PRICE_ID:}

# Mail
spring.mail.host=${SPRING_MAIL_HOST:}
spring.mail.port=${SPRING_MAIL_PORT:}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=true
app.mail.from=${MAIL_FROM:}
# App
app.frontend.url=${APP_FRONTEND_URL:}



