spring.application.name=gotcha-api
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gotcha-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

aws.accessKey=${AWS_ACCESS_KEY:}
aws.secretKey=${AWS_SECRET_KEY:}
aws.region=${AWS_REGION:eu-north-1}
aws.bucket-name=${AWS_BUCKET_NAME:}

logging.file.name=logs/gotcha.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %level - %logger - %msg%n
logging.level.root=INFO

spring.datasource.hikari.auto-commit=false

logging.level.org.springframework.security=DEBUG

stripe.secret-key=${STRIPE_SECRET_KEY:}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:}
stripe.price-id=${STRIPE_PRICE_ID:}

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# Mail configuration
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:gotcha.project.app@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:spem uvle tabh wdrw}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend URL for password reset link
app.frontend.url=${FRONTEND_URL:http://localhost:3000}