spring.application.name=gotcha-api
spring.datasource.url=jdbc:postgresql://localhost:5432/gotcha
spring.datasource.username = postgres
spring.datasource.password = admin
spring.datasource.drive-class-name = org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql = true

aws.accessKey=AKIAWZA7FKR6JKYYBZNO
aws.secretKey=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
aws.region=eu-west-1
aws.bucket.name=gotcha-cafe-images-eu

logging.file.name=logs/gotcha.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %level - %logger - %msg%n
logging.level.root=INFO

spring.datasource.hikari.auto-commit=false

logging.level.org.springframework.security=DEBUG

stripe.secret.key=sk_test_51T8RqpHk0gTF58U3iFl6hWkus9qvosjI4XkCxgg1nB8NlkBvDzYbQ8Ht41LjGP4ml8WwZ9G5NfULXeJb8DALK1Zu00AZ8Q26QQ 
stripe.price.id=price_1T8fi5Hk0gTF58U3LxMSp8Z2